# Generated by Django 4.1.1 on 2022-10-02 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uni_number',
            field=models.CharField(default='', max_length=9, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
