# Generated by Django 4.1.1 on 2022-10-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_name_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.AddField(
            model_name='student',
            name='firstt_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
