# Generated by Django 4.1.1 on 2022-10-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_profile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
