# Generated by Django 4.1.1 on 2022-10-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_grades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
